env:
  K8S_NAMESPACE: "kube-system"
  K8S_CLUSTER_NAME: "tf-sample-cluster"
  SERVICE_ACCOUNT_NAME: "alb-ingress-controller"
  POLICY_NAME: "ExternalDNSServiceAccountPolicy"
steps:
  - label: ":male-scientist: Deploy external-dns."
    command:
      - ".buildkite/scripts/deploy.sh"
    plugins:
      - 'uber-workflow/run-without-clone':      
    timeout_in_minutes: 10